### ISSUE TITLE
"You must not crawl, scrape, or otherwise cache any content from Instagram including but not limited to user profiles and photos."

### ISSUE THREAD

**Issue by InvisibleOS** [fernandod1/Instagram-to-discord#13]
I have researched about this a little bit and found out that this is against the [Terms and Use of Instagram](https://www.instagram.com/about/legal/terms/before-january-19-2013/), under Basic Terms, number `10.`. This is the only thing stopping me from using this code. Otherwise, the code is amazing.

**Comment by fernandod1** [comment]
I would say google images does not respect it.

**Comment by InvisibleOS** [comment]
Okay so this works on google images?
