### ISSUE TITLE
No me funciona y no se por que

### ISSUE THREAD

**Issue by ghost** [fernandod1/Instagram-to-discord#15]
Hola muy buenos días, disculpen mi inexperiencia pero soy bastante nuevo en python. He visto tu código y me parece genial, solo que tengo un problema para hacerlo funcionar, me pide el nombre de usuario de la cuenta de instagram y el url webhook, pero no se donde poner este último (ya lo he generado), ya eh intentado y solo me da error. Crees que podrías ayudarme?

**Comment by onelightyearrrrr** [comment]
https://github.com/fernandod1/Instagram-to-discord/pull/16#issue-583886668

**Comment by fernandod1** [comment]
Hola, debes crear 3 variables de entorno en el sistema antes de ejecutar el script. Puedes leer el archivo readme de https://github.com/fernandod1/Instagram-to-discord para saber como crear las variables de entorno.
