### ISSUE TITLE
How to configure it properly !

### ISSUE THREAD

**Issue by emirilkkutlu** [fernandod1/Instagram-to-discord#19]
It always says I didn't configure it properly, please help me

**Comment by kasimlone** [comment]
Getting the same issue after replacing the variables.

Please configure environment variables properly!

**Comment by fernandod1** [comment]
Be sure you set correctly enviroment variables:

Set IG_USERNAME to username account you want to monitor. Example: ladygaga
Set WEBHOOK_URL to Discord account webhook url. To know how, just Google: "how to create webhook discord".
Set TIME_INTERVAL to the time in seconds in between each check for a new post. Example: 1.5, 600 (default=600 = 10 minutes)

How to setup enviroment variables:
https://www.serverlab.ca/tutorials/linux/administration-linux/how-to-set-environment-variables-in-linux/
