### ISSUE TITLE
"An error ocurred" after a few tries.

### ISSUE THREAD

**Issue by tavarex** [fernandod1/Instagram-to-discord#2]
The code was working perfectly, I added one "while" loop and it works well, but after a lot of scrapes it came "an error ocurred", so I just deleted everything and downloaded it again, and it stills give me "An error ocurred" after the fresh install.

**Comment by fernandod1** [comment]
Hi,
you only modified one line? Have you tried to execute original script and actually returns error too?

**Comment by tavarex** [comment]
Yes just added the loop, actually I found what was going on, I was soft banned from my ip adress for trying too mutch times, I heard that you need 1 hour of delay to do dont get ip banned, thanks a lot!



Em 18 de set. de 2020, à(s) 21:28, Fernando <notifications@github.com> escreveu:

﻿

Hi,
you only modified one line? Have you tried to execute original script and actually returns error too?

**Comment by fernandod1** [comment]
Oh, nice you found solution. I did not know about that "soft ban" feature, thanks for update.

**Comment by vaish-vs** [comment]
Oh it's a softban? I just had the same error and I was wondering why.
