### ISSUE TITLE
for multiple username

### ISSUE THREAD

**Issue by abue-ammar** [fernandod1/Instagram-to-discord#6]
what if i want to monitor multiple user?? how do i do that

**Comment by K1udg3** [comment]
Seems like you could just run multiple instances of the script. Not sure haven't tried it.

**Comment by fernandod1** [comment]
It can be easily done with minor change in code so its passed to script one argument called username to monitor. Then create a conjob for each username to monitor. Check https://unix.stackexchange.com/questions/237443/is-it-possible-to-pass-arguments-into-a-python-script

Another option is to create a list of usernames to monitor, loop them, and just using one cronjob execution, check all usernames.

**Comment by abue-ammar** [comment]
alrighty i will try that
