### ISSUE TITLE
Is there a way to flip it ? 

### ISSUE THREAD

**Issue by K1udg3** [fernandod1/Instagram-to-discord#7]
I was wondering if it could be flipped to take the photos from our memes section of the discord and post it to instagram?

**Comment by fernandod1** [comment]
Yes. You can request discord api to get images, verify if already posted in instagram conparing with a temporary database and post them in instagram using api if not posted yet.

This is a totally opposite idea that would require to be coded from zero. Looks intetesting idea, I will code it, but actually I dont have free time. :(

Thank you.
