### ISSUE TITLE
Stop working.

### ISSUE THREAD

**Issue by EmreKLC414** [fernandod1/Instagram-to-discord#8]
Hello! When i start the bot just send last pic to channel, when i send new post its doing nothing everytime i need to type "instagram-discord.py" to terminal for posting new image i dont understand why. Thanks for this perfect bot :)

**Comment by fernandod1** [comment]
For automatize process of posting new images, you must setup a cronjob that executes script every X minutes/hours, Example: https://www.activecampaign.com/help/setting-up-a-cron-job/

If you host your website in a CPanel or Plesk server, its very easy to create a cronjob.

**Comment by EmreKLC414** [comment]
i dont have a website :S just windows server. if i decided to change webhook to discord bot is it work well without cron job ? is that possible ?

**Comment by fernandod1** [comment]
If you are usnig Windows O.S. you can automate python script execution using Task Scheduler for example. Check: https://towardsdatascience.com/automate-your-python-scripts-with-task-scheduler-661d0a40b279

**Comment by EmreKLC414** [comment]
`INSTAGRAM_USERNAME = "" # Example: ladygaga
WEBHOOK_URL = ""                # Url to your discord webhook
DATABASE = "database.txt"`

`INSTAGRAM_USERNAME = "" # Example: ladygaga
BOT_TOKEN = ""                # Bot Tken
DATABASE = "database.txt"`

if i change like that is that work with bot without tasks or cronjob ?

**Comment by fernandod1** [comment]
A task or cronjob setup is a must to monitor new posts in Instagram.

**Comment by EmreKLC414** [comment]
ah you don't understand :) my question is how can i add this to our bot task or cronjob is problem for our windows server i want to implement to our bot or create new one for that my question is; is that possible ?

**Comment by fernandod1** [comment]
I recommend setup scheduled task to execute script in your windows server.
